---
- name: Converge
  hosts: localhost
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 900
      when: ansible_os_family == 'Debian'

  roles:
    - role: tinyblargon.go
      vars:
        go_version: "1.24.1"
        go_checksum: "sha256:cb2396bae64183cdccf81a9a6df0aea3bce9511fc21469fb89a0c00470088073"
        go_state: "present"
